### ISSUE TITLE
Download and run of msi file has error

### ISSUE THREAD

**Issue by imagineer64** [gdeckler/MicrosoftHatesGregsQuickMeasures#4]
![image](https://user-images.githubusercontent.com/14917505/154858724-d74bef45-acc8-4c2b-ade2-8c498f21d22d.png)

My guess is if someone has never installed an External Tool then the installer fails because there is no path:
C:\Program Files (x86)\Common Files\Microsoft Shared\Power BI Desktop\External Tools

I also believe the above path is only if you chose "install everyone" option and maybe a different path for "install only me".

As a workaround I manually created the above path and the installer worked as expected.

**Comment by gdeckler** [comment]
I have updated the installer to create the necessary directory structure if it does not exist. The installer now checks if the "Power BI Desktop" directory exists within the "C:\Program Files (x86)\Common Files\Microsoft Shared\" directory and if it does not, creates it. Also the installer then checks to see if the "External Tools" directory exists within the "C:\Program Files (x86)\Common Files\Microsoft Shared\Power BI Desktop" directory and if it does not, creates it. 

Thanks for this issue report, I just ran into this with someone else!

**Comment by imagineer64** [comment]
Thanks @gdeckler!
Another note is that I think the install location is different depending on if someone chooses to install for everyone or just the primary user ie I think shared is used for the everyone option.

**Comment by gdeckler** [comment]
I tested this. It appears that regardless of the installation mode Everyone or Just Me. It appears that the following path is used for both options.
C:\Program Files (x86)\Common Files\Microsoft Shared\Power BI Desktop\External Tools
If there is some nuance to this I'll have to wait for someone to find it as I can't currently reproduce any alternate path for where the external tool json files need to be located.
